### ISSUE TITLE
Cannot run editor on linux

### ISSUE THREAD

**Issue by deveee** [mcsab/stk-editor#19]
I'm not sure if there is something wrong in code or I'm doing something wrong... Few more words in README would be great.

I patched your irrlicht version to allow to compile it with mesa 10. Now I'm able to compile STK editor. But what's next? Where should I place executable file? I tried to do:
```
> supertuxkart
>>> data
>>>>> editor
>>>>> karts
>>>>> tracks
>>>>> textures
>>>>> (...)
>>> stk-editor
```

But it says that it cannot find textures directory: ```Could not create archive for: textures``` and it segfaults.

```
(gdb) bt full
#0  0x0000000000422489 in NewDialogWndw::reallocate (this=0x0, ss=...)
    at src/gui/new_dialog_wndw.cpp:83
No locals.
#1  0x000000000041993b in Editor::run (this=0xb81310) at src/editor.cpp:697
        current_time = 68
        last_time = 0
#2  0x000000000041e9b5 in main (argc=1, argv=0x7fffffffe618) at src/main.cpp:11
        editor = 0xb81310
```

I also tried to place it directly into data folder. In this case it doesn't report any issues, but it still cannot run (segfault with large backtrace).

**Comment by deveee** [comment]
Okay, it runs when I changed this line in editor
```
diff --git a/src/editor.cpp b/src/editor.cpp
index a53126d..fdc9b82 100644
--- a/src/editor.cpp
+++ b/src/editor.cpp
@@ -694,7 +694,7 @@ bool Editor::run()
                 if (m_tex_sel) m_tex_sel->reallocate();
                 if (m_rcs)     m_rcs->reallocate();
                 if (m_indicator) m_indicator->reallocate();
-                m_new_dialog_wndw->reallocate(m_screen_size);
+                if (m_new_dialog_wndw) m_new_dialog_wndw->reallocate(m_screen_size);
             }
             last_time = current_time;
         } // isWindowActive
```

**Comment by hiker** [comment]
As suggested by deve, I have forked the editor into supertuxkart, and given you write permission to it :)
